add some rule makefile
raphaelMrci/Epigen pull request #4
Opened 2022-01-14 21:29 UTC by Saverio976

2022-01-14 22:43 UTC, raphaelMrci requested changes
Waw, magnifique Makefile! 

Faudrait juste que tu enlèves les NAME, et on est bon! Je t'avoues que c'est la première fois que je fais une "review", donc je sais pas si je peux modifier ton code avant de le merge ou pas, donc voilà, faut juste faire cette modification, et c'est méga mergable!

2022-01-14 22:43 UTC, raphaelMrci commented on makefile_file
> +NAME		=	UwU
Alors, le NAME est ajouté par le programme ^^'

2022-01-15 01:47 UTC, Saverio976 commented
oki, didn't see that,
sorry to be late but, i just remove the NAME

2022-01-15 11:35 UTC, raphaelMrci approved these changes
Perfect !

2022-01-15 11:35 UTC, merged